#include "rdtest.h"
#include "rdtest_helpers.h"
#include <redasm/redasm.h>

/*
 * rd_get_address resolves a name back to an address. Two paths:
 *
 *   - a real name in the DB
 *   - an autogenerated name, of the form <prefix>[[n]]_<UPPERHEX>
 *
 * The second path is validated by round-tripping through rd_i_get_name:
 * a string resolves only if it is exactly what that address generates.
 * These tests pin that, because every looser rule admits false positives
 * (any string ending in _<hex> would resolve to that address).
 */

#define TEST_SEG_START 0x1000
#define TEST_SEG_SIZE 0x1000

static RDContext* _setup(void) {
    RDContext* ctx = rdtest_context_create();
    if(!ctx) return NULL;

    rd_map_segment_n(ctx, "TEST", TEST_SEG_START, TEST_SEG_SIZE,
                     RD_SP_R | RD_SP_X);
    return ctx;
}

static bool _resolves_to(RDContext* ctx, const char* name, RDAddress expected) {
    RDAddress got = 0;
    return rd_get_address(ctx, name, &got) && got == expected;
}

static bool _rejects(RDContext* ctx, const char* name) {
    RDAddress got = 0;
    return !rd_get_address(ctx, name, &got);
}

// --- real names ---

static int test_real_name(void) {
    RDContext* ctx = _setup();
    rdtest_assert_notnull(ctx);

    rd_library_name(ctx, TEST_SEG_START + 0x10, "my_function");
    rdtest_assert(_resolves_to(ctx, "my_function", TEST_SEG_START + 0x10),
                  "real name did not resolve");

    rd_destroy(ctx);
    return RDTEST_PASS;
}

static int test_real_name_wins_over_autogenerated(void) {
    // a named address must not also resolve under its autogenerated form,
    // because rd_i_get_name returns the real name there
    RDContext* ctx = _setup();
    rdtest_assert_notnull(ctx);

    rd_library_name(ctx, TEST_SEG_START, "named");
    rdtest_assert(_rejects(ctx, "loc_1000"),
                  "autoname resolved on a named address");

    rd_destroy(ctx);
    return RDTEST_PASS;
}

// --- autogenerated: loc / sub ---

static int test_autogenerated_loc(void) {
    RDContext* ctx = _setup();
    rdtest_assert_notnull(ctx);

    rdtest_assert(_resolves_to(ctx, "loc_1000", TEST_SEG_START),
                  "loc_ did not resolve");

    rd_destroy(ctx);
    return RDTEST_PASS;
}

// --- rejection cases ---

static int test_rejects_arbitrary_prefix(void) {
    // the regression this whole design exists for: a random prefix with a
    // valid hex tail must not resolve
    RDContext* ctx = _setup();
    rdtest_assert_notnull(ctx);

    rdtest_assert(_rejects(ctx, "hgjhdfjkgh_1000"),
                  "arbitrary prefix resolved");
    rdtest_assert(_rejects(ctx, "my_buffer_1000"), "arbitrary prefix resolved");

    rd_destroy(ctx);
    return RDTEST_PASS;
}

static int test_rejects_leading_zeros(void) {
    // %llX never emits them, so this is not a name any address generates
    RDContext* ctx = _setup();
    rdtest_assert_notnull(ctx);

    rdtest_assert(_rejects(ctx, "loc_0001000"), "leading zeros resolved");

    rd_destroy(ctx);
    return RDTEST_PASS;
}

static int test_rejects_lowercase(void) {
    RDContext* ctx = _setup();
    rdtest_assert_notnull(ctx);

    rdtest_assert(_resolves_to(ctx, "loc_1ABC", TEST_SEG_START + 0xABC),
                  "uppercase did not resolve");
    rdtest_assert(_rejects(ctx, "loc_1abc"), "lowercase resolved");

    rd_destroy(ctx);
    return RDTEST_PASS;
}

static int test_rejects_unmapped(void) {
    RDContext* ctx = _setup();
    rdtest_assert_notnull(ctx);

    rdtest_assert(_rejects(ctx, "loc_DEADBEEF"), "unmapped address resolved");
    rdtest_assert(_rejects(ctx, "loc_0"), "unmapped address resolved");

    rd_destroy(ctx);
    return RDTEST_PASS;
}

static int test_rejects_malformed(void) {
    RDContext* ctx = _setup();
    rdtest_assert_notnull(ctx);

    rdtest_assert(_rejects(ctx, NULL), "NULL resolved");
    rdtest_assert(_rejects(ctx, ""), "empty string resolved");
    rdtest_assert(_rejects(ctx, "loc"), "no underscore resolved");
    rdtest_assert(_rejects(ctx, "loc_"), "empty hex tail resolved");
    rdtest_assert(_rejects(ctx, "_1000"), "no prefix resolved");
    rdtest_assert(_rejects(ctx, "loc_XYZ"), "non-hex resolved");
    rdtest_assert(_rejects(ctx, "loc_1000 "), "trailing space resolved");

    rd_destroy(ctx);
    return RDTEST_PASS;
}

static int test_rejects_overflow(void) {
    // must fail cleanly, not abort: this is reachable from a goto dialog
    RDContext* ctx = _setup();
    rdtest_assert_notnull(ctx);

    rdtest_assert(_rejects(ctx, "loc_FFFFFFFFFFFFFFFFFFFFFFFF"),
                  "overflow resolved");
    rdtest_assert(_rejects(ctx, "loc_10000000000000000"), "overflow resolved");

    rd_destroy(ctx);
    return RDTEST_PASS;
}

// --- typed data and array elements ---

static int test_autogenerated_type(void) {
    RDContext* ctx = _setup();
    rdtest_assert_notnull(ctx);

    rd_library_type(ctx, TEST_SEG_START + 0x200, "u32", 0, RD_TYPE_NONE);

    rdtest_assert(_resolves_to(ctx, "u32_1200", TEST_SEG_START + 0x200),
                  "typed address did not resolve");
    rdtest_assert(_rejects(ctx, "loc_1200"), "loc_ resolved on typed address");

    rd_destroy(ctx);
    return RDTEST_PASS;
}

static int test_autogenerated_array_element(void) {
    RDContext* ctx = _setup();
    rdtest_assert_notnull(ctx);

    // 4 x u32 at 0x1300
    rd_library_type(ctx, TEST_SEG_START + 0x300, "u32", 4, RD_TYPE_NONE);

    rdtest_assert(_resolves_to(ctx, "u32[0]_1300", TEST_SEG_START + 0x300),
                  "element 0 did not resolve");
    rdtest_assert(_resolves_to(ctx, "u32[2]_1308", TEST_SEG_START + 0x308),
                  "element 2 did not resolve");
    rdtest_assert(_resolves_to(ctx, "u32[3]_130C", TEST_SEG_START + 0x30C),
                  "element 3 did not resolve");

    // the index must be the one the address actually implies
    rdtest_assert(_rejects(ctx, "u32[1]_1308"), "wrong index resolved");
    rdtest_assert(_rejects(ctx, "u32_1308"), "missing index resolved");

    rd_destroy(ctx);
    return RDTEST_PASS;
}

// --- the invariant ---

static int test_round_trip(void) {
    RDContext* ctx = _setup();
    rdtest_assert_notnull(ctx);

    rd_set_function(ctx, TEST_SEG_START + 0x100);
    rd_library_type(ctx, TEST_SEG_START + 0x200, "u32", 0, RD_TYPE_NONE);
    rd_library_type(ctx, TEST_SEG_START + 0x300, "u32", 4, RD_TYPE_NONE);
    rd_library_name(ctx, TEST_SEG_START + 0x400, "explicit_name");

    static const RDAddress ADDRS[] = {
        TEST_SEG_START,         TEST_SEG_START + 0x100, TEST_SEG_START + 0x200,
        TEST_SEG_START + 0x300, TEST_SEG_START + 0x304, TEST_SEG_START + 0x30C,
        TEST_SEG_START + 0x400, TEST_SEG_START + 0x555,
    };

    for(usize i = 0; i < sizeof(ADDRS) / sizeof(ADDRS[0]); i++) {
        const char* name = rd_get_name(ctx, ADDRS[i]);
        rdtest_assert_notnull(name);

        RDAddress got = 0;
        rdtest_assert(rd_get_address(ctx, name, &got),
                      "generated name did not resolve");
        rdtest_assert_eq(got, ADDRS[i]);
    }

    rd_destroy(ctx);
    return RDTEST_PASS;
}

static int test_null_out_param(void) {
    // rd_get_address(ctx, name, NULL) is a valid existence check
    RDContext* ctx = _setup();
    rdtest_assert_notnull(ctx);

    rdtest_assert(rd_get_address(ctx, "loc_1000", NULL), "NULL out failed");
    rdtest_assert(!rd_get_address(ctx, "loc_DEADBEEF", NULL),
                  "NULL out resolved unmapped");

    rd_destroy(ctx);
    return RDTEST_PASS;
}

// clang-format off
static const RDTest K_TESTS[] = {
    {"real_name", test_real_name},
    {"real_name_wins_over_autogenerated", test_real_name_wins_over_autogenerated},
    {"autogenerated_loc", test_autogenerated_loc},
    {"rejects_arbitrary_prefix", test_rejects_arbitrary_prefix},
    {"rejects_leading_zeros", test_rejects_leading_zeros},
    {"rejects_lowercase", test_rejects_lowercase},
    {"rejects_unmapped", test_rejects_unmapped},
    {"rejects_malformed", test_rejects_malformed},
    {"rejects_overflow", test_rejects_overflow},
    {"autogenerated_type", test_autogenerated_type},
    {"autogenerated_array_element", test_autogenerated_array_element},
    {"round_trip", test_round_trip},
    {"null_out_param", test_null_out_param},
    {NULL, NULL},
};
// clang-format on

int main(int argc, char** argv) {
    rdtest_init(argc, argv);
    int result = rdtest_run("naming", K_TESTS);
    rdtest_deinit();
    return result;
}
